version: "3"
services:
  beanstalk:
    image: ghcr.io/sammousa/beanstalkd:latest
  phpunit:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-phpunit
    environment:
      SERVER_HOST: beanstalk
    depends_on:
      - beanstalk
    volumes:
      - ./:/app:ro
      - ./.phpunit.result.cache:/app/.phpunit.result.cache:rw
      - ./tests/coverage:/coverage:rw
    command:
      - --coverage-clover
      - /coverage/coverage.xml
      - --coverage-html
      - /coverage
