name: Continous integration
on: [push, pull_request]
jobs:
  tests: Tests
    runs-on: ubuntu-latest
    services:
      beanstalk:
        image: schickling/beanstalkd
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install dependencies including dev
        run: composer install
      - name: Tests
        run: docker-compose run --rm phpunit
      - uses: codecov/codecov-action@v2
        with:
          files: ./tests/coverage/coverage.xml
          flags: unittests
          name: codecov-umbrella
  code_checks:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: symplify/easy-coding-standard, phpstan, phpunit
      - name: Test code style
        run: ecs
      - name: Install dependencies
        run: composer install --no-dev
      # This is disabled due to errors in the baseline, re-enable it when those have been fully cleaned.
      #- name: Static analysis
      #  run: phpstan analyse src
      - name: Install dependencies including dev
        run: composer install
      # We run static analysis with dev dependencies due to baseline errors, when those have been cleaned we run them on
      # src and tests separately, this allows us to detect accidental usage of dev dependencies in src.
      - name: Static analysis
        run: phpstan
      # This is disabled due to errors in the baseline, re-enable it when those have been fully cleaned.
      #- name: Static analysis of tests
      #  run: phpstan analyse tests
  commitlint:
    name: commit-lint
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-commit-lint@v1
        with:
         config: conventional
  docs:
    name: Docs
    needs:
      - code_checks
      - tests
      - commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpDocumentor
      - name: Generate docs
        run: phpdoc run
      - name: Deploy docs to pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
  release:
    name: Automated release
    needs:
      - code_checks
      - tests
      - commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: >
          npx
          -p "@semantic-release/commit-analyzer"
          -p "@semantic-release/release-notes-generator"
          -p conventional-changelog-conventionalcommits
          -p semantic-release
          -- semantic-release 
          --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
